# Generated by Django 4.1 on 2023-02-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='c_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='c_author_updated',
            new_name='author_updated',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='c_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='c_date_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='c_date_updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='c_title',
            new_name='title',
        ),
    ]
