# Generated by Django 4.1 on 2023-02-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_rename_c_author_content_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='topic',
            field=models.CharField(default='BLOG', max_length=40),
        ),
    ]
