# Generated by Django 4.1 on 2023-05-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_rename_user_id_posts_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shares',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='shares',
            old_name='user_id',
            new_name='user',
        ),
    ]
