# Generated by Django 4.1 on 2023-03-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_content_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='lnk',
            field=models.CharField(default='lnk', max_length=100),
        ),
    ]
