# Generated by Django 4.1 on 2023-08-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_rename_post_id_comments_post_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shares',
            table='shares',
        ),
    ]
