# Generated by Django 4.1 on 2023-03-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_content_lnk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='author_updated',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='date_updated',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
