# Generated by Django 4.1 on 2023-11-22 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_like_rename_comments_comment_rename_posts_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contents.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.SlugField(default=''),
        ),
    ]
