# Generated by Django 4.1 on 2023-11-22 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_alter_comment_post_alter_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='contents.post'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
