# Generated by Django 4.1 on 2023-11-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_alter_share_post_alter_post_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_commented_link',
        ),
    ]
