# Generated by Django 4.1 on 2023-11-28 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_remove_comment_post_commented_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='post_shared_link',
        ),
    ]
