# Generated by Django 4.1 on 2024-01-04 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0010_remove_share_post_shared_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='shared_with',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shareduser', to=settings.AUTH_USER_MODEL),
        ),
    ]
