# Generated by Django 4.1 on 2023-04-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_of_post', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('pic_of_user', models.TextField()),
                ('date_created', models.DateField()),
                ('date_updated', models.DateField(null=True)),
                ('link', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'blog_users',
            },
        ),
    ]
